parameters:
#    inodata_invoicer.example.class: Inodata\InvoicerBundle\Example

services:
    invoicer.email_reader:
        class: Inodata\InvoicerBundle\Lib\EmailReader
        arguments: [ "%email_acount%", "%invoicer_email%", "%invoicer_password%", @service_container ]
